version: "3.8"

services:
  mongo:
    image: mongo:6
    ports:
      - "27017:27017" # Expose for local dev if needed
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=cphere_db
    networks:
      - cphere-net

  backend:
    image: masterboy376/cphere-backend:v1.0.0
    env_file:
      - ./backend/.env.prod
    environment:
      - APP_ENV=production
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - cphere-net

  frontend:
    image: masterboy376/cphere-frontend:v1.0.0
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - cphere-net

volumes:
  mongo_data:

networks:
  cphere-net:
