version: "3.8"

services:
  mongo:
    image: mongo:6
    volumes:
      - mongo_data:/data/db
    ports:
      - "${MONGO_HOST_PORT}:27017"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: ${BACKEND_BUILD_TARGET}      # either “builder” or “runtime”
    image: cphere-backend:${TAG:-latest}
    env_file:
      - backend/.env${ENV_SUFFIX}           # picks .env.development or .env.prod
    environment:
      - APP_ENV=${APP_ENV}
    command: ${BACKEND_COMMAND}           # overrides CMD in dev
    ports:
      - "${BACKEND_HOST_PORT}:8080"
    volumes:
      - ${BACKEND_VOLUME:-}               # e.g. “./backend:/usr/src/app” in dev

    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: ${FRONTEND_BUILD_TARGET}    # “builder” or “runtime”
    image: cphere-frontend:${TAG:-latest}
    env_file:
      - frontend/.env${ENV_SUFFIX}
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    command: ${FRONTEND_COMMAND}
    ports:
      - "${FRONTEND_HOST_PORT}:80"
    volumes:
      - ${FRONTEND_VOLUME:-}             # e.g. “./frontend:/usr/src/app” in dev

    depends_on:
      - backend

volumes:
  mongo_data:
